/**
 * Generates src/icons.generated.mjs from the Lucide icon set.
 *
 * The landing page ships as plain static files, so it cannot import a React icon
 * component at runtime. Reading the upstream icon nodes keeps the marketing icons
 * identical to the product icons instead of re-drawing SVG paths by hand.
 *
 * `lucide-react` is pinned here to the version the SynqDrive product frontend
 * depends on. Bump both together, or the marketing icons drift from the product.
 *
 * Usage: npm run icons
 */
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const LUCIDE = path.resolve(ROOT, 'node_modules', 'lucide-react', 'dist', 'esm', 'icons');
const OUT = path.join(ROOT, 'src', 'icons.generated.mjs');

const ICONS = [
  // Navigation and controls
  'chevron-down',
  'menu',
  'x',
  'globe',
  'arrow-right',
  // Unified operations capabilities
  'database',
  'git-merge',
  'layers',
  'users',
  // Platform capability categories
  'car',
  'credit-card',
  'user-check',
  'message-circle',
  'file-text',
  'code-xml',
];

/** Attribute order Lucide itself renders, so generated markup stays stable. */
const ATTR_ORDER = [
  'd',
  'cx',
  'cy',
  'r',
  'rx',
  'ry',
  'x',
  'y',
  'x1',
  'x2',
  'y1',
  'y2',
  'width',
  'height',
  'points',
];

/**
 * Lucide ships icons as ES modules that import a React factory. Parsing the
 * exported `__iconNode` array literal avoids loading React in this build step.
 */
function parseIconNode(source, name) {
  const start = source.indexOf('const __iconNode = [');
  if (start === -1) throw new Error(`no __iconNode in ${name}`);
  const open = source.indexOf('[', start);
  let depth = 0;
  let end = -1;
  for (let i = open; i < source.length; i += 1) {
    if (source[i] === '[') depth += 1;
    if (source[i] === ']') {
      depth -= 1;
      if (depth === 0) {
        end = i + 1;
        break;
      }
    }
  }
  if (end === -1) throw new Error(`unterminated __iconNode in ${name}`);

  const literal = source
    .slice(open, end)
    // Quote bare object keys so the array literal becomes valid JSON-ish input.
    .replace(/([{,]\s*)([A-Za-z_][\w-]*)\s*:/g, '$1"$2":')
    .replace(/,(\s*[\]}])/g, '$1');

  // eslint-disable-next-line no-new-func -- build-time parse of a vendored literal
  return new Function(`return ${literal};`)();
}

function toSvg(nodes) {
  const children = nodes
    .map(([tag, attrs]) => {
      const printable = Object.entries(attrs).filter(([key]) => key !== 'key');
      printable.sort((a, b) => {
        const ai = ATTR_ORDER.indexOf(a[0]);
        const bi = ATTR_ORDER.indexOf(b[0]);
        return (ai === -1 ? 99 : ai) - (bi === -1 ? 99 : bi);
      });
      const rendered = printable.map(([key, value]) => `${key}="${value}"`).join(' ');
      return `<${tag} ${rendered}/>`;
    })
    .join('');

  return (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" ' +
    'stroke="currentColor" stroke-width="1.5" stroke-linecap="round" ' +
    `stroke-linejoin="round" aria-hidden="true" focusable="false">${children}</svg>`
  );
}

async function main() {
  const entries = [];
  for (const name of ICONS) {
    const source = await readFile(path.join(LUCIDE, `${name}.js`), 'utf8');
    entries.push([name, toSvg(parseIconNode(source, name))]);
  }

  const version = JSON.parse(
    await readFile(path.resolve(ROOT, 'node_modules', 'lucide-react', 'package.json'), 'utf8'),
  ).version;

  const body = entries.map(([name, svg]) => `  '${name}': ${JSON.stringify(svg)},`).join('\n');
  const file = `/**
 * Generated by landingpage/tools/build-icons.mjs. Do not edit by hand.
 *
 * Source: lucide-react@${version}, ISC licensed. Same version as the product frontend.
 * Regenerate with: npm run icons
 */
export const icons = {
${body}
};

export function icon(name) {
  const svg = icons[name];
  if (!svg) throw new Error(\`unknown icon: \${name}\`);
  return svg;
}
`;

  await writeFile(OUT, file, 'utf8');
  console.log(`wrote ${path.relative(ROOT, OUT)} with ${entries.length} icons from lucide-react@${version}`);
}

await main();
